language: java

addons:
  hostname: jyshort

  homebrew: # only active on osx
    update: true
    packages:
      - ant


matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - ant
      jdk: openjdk8

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - ant
      jdk: openjdk11

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - ant
      jdk: openjdk12

    - os: osx
      osx_image: xcode9.3 # Last supporting Java 8
      jdk: oraclejdk8


install:
  - ant developer-build


script:
  - ant regrtest-travis

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net
